#include <glib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>


#ifndef CORENLP_DOCUMENT_H
#define CORENLP_DOCUMENT_H

typedef enum dep_t { 
    TD_NONE=0, 
    TD_ROOT=1, 
    TD_NSUBJ=2, 
    TD_NN=3,
    TD_COP=4, 
    TD_DET=5,
    TD_POS=6,
    TD_AMOD=7,
    TD_DOBJ=8,
    TD_PREP_OF=9,
    TD_PREP_IN=10,
    TD_PREP_FOR=11,
    TD_PREP_OVER=12,
    TD_PREP_AFTER=13,
    TD_CONJ_AND=14,
    TD_CONJ_OR=15,
    TD_TMOD=16,
    TD_MARK=17,
    TD_VMOD=18,
    TD_ADVCL=19,
    TD_AGENT=20,
    TD_AUX=21,
    TD_CCOMP=22,
    TD_NEG=23,
    TD_ADVMOD=24,
    TD_APPOS=25,
    TD_NSUBJPASS=26,
    TD_AUXPASS=27,
    TD_NUM=28,
    TD_DEP=29,
    TD_POBJ=30,
    TD_PREP_FROM=31,
    TD_CONJ_BUT=32,
    TD_PREPC_INCLUDING=33,
    TD_PRT=34,
    TD_CC=35,
    TD_XCOMP=36,
    TD_PREP_WITH=37,
    TD_PREP_AT=38,
    TD_PREP_UNDER=39,
    TD_PREP_TO=40,
    TD_RCMOD=41,
    TD_PREPC_OUTSIDE=42,
    TD_POSSESSIVE=43,
    TD_PREP=44,
    TD_PCOMP=45,
    TD_PREP_ON=46,
    TD_PREP_INTO=47,
    TD_PREPC_FOR=48,
    TD_PREP_BY=49,
    TD_PREP_AS=50,
    TD_PREPC_TO=51,
    TD_PRECONJ=52,
    TD_CONJ_NOR=53,
    TD_PREP_ABOUT=54,
    TD_PREPC_AFTER=55,
    TD_PREP_AGAINST=56,
    TD_PREP_ALONG=57,
    TD_PREP_BEHIND=58,
    TD_IOBJ=59,
    TD_NPADVMOD=60,
    TD_PREPC_BY=61,
    TD_PREP_OUTSIDE=62,
    TD_PREP_DURING=63,
    TD_PREPC_FROM=64,
    TD_PREP_INCLUDING=65,
    TD_EXPL=66,
    TD_CSUBJ=67,
    TD_MWE=68,
    TD_QUANTMOD=69,
    TD_PREPC_BECAUSE_OF=70,
    TD_PREPC_IN=71,
    TD_NUMBER=72,
    TD_PREP_SINCE=73,
    TD_PREPC_OF=74,
    TD_PARATAXIS=75,
    TD_PREP_BETWEEN=76,
    TD_PREP_LIKE=77,
    TD_PREPC_WHILE=78,
    TD_PREP_WITHOUT=79,
    TD_PREP_TOWARD=80,
    TD_PREP_ALONGSIDE=81,
    TD_ACOMP=82,
    TD_PREP_AROUND=83,
    TD_PREP_ONTO=84,
    TD_PREPC_BEFORE=85,
    TD_PREP_UNTIL=86,
    TD_PREP_BECAUSE=87,
    TD_PREP_BECAUSE_OF=88,
    TD_PREP_AMONG=89,
    TD_PREDET=90,
    TD_PREP_DESPITE=91,
    TD_PREP_THAT=92,
    TD_PREP_THAN=93,
    TD_CONJ_NEGCC=94,
    TD_PREP_THROUGH=95,
    TD_DISCOURSE=96,
    TD_PREPC_ABOUT=97,
    TD_PREP_ACROSS=98,
    TD_PREP_OUT=99,
    TD_PREP_AWAY_FROM=100,
    TD_PREP_INSIDE=101,
    TD_PREP_NEAR=102,
    TD_PREP_THROUGHOUT=103,
    TD_PREP_DOWN=104,
    TD_PREPC_WITH=105,
    TD_PREP_ABOVE=106,
    TD_PREP_SUCH_AS=107,
    TD_CSUBJPASS=108,
    TD_PREP_PER=109,
    TD_PREP_UPON=110,
    TD_PREPC_DESPITE=111,
    TD_CONJ_PLUS=112,
    TD_PREP_OUT_OF=113,
    TD_PREP_AMID=114,
    TD_PREPC_AT=115,
    TD_PREPC_COMPARED_WITH=116,
    TD_PREPC_ACCORDING_TO=117,
    TD_PREPC_ON=118,
    TD_PREP_WITHIN=119,
    TD_PREPC_WITHOUT=120,
    TD_PREP_ATOP=121,
    TD_PREP_AS_OF=122,
    TD_PREPC_AS_OF=123,
    TD_PREPC_INSIDE=124,
    TD_PREPC_CLOSE=125,
    TD_PREPC_CLOSE_TO=126,
    TD_PREP_BEFORE=127,
    TD_PREP_AHEAD_OF=128,
    TD_PREP_IN_ADDITION_TO=129,
    TD_PREPC_SINCE=130,
    TD_PREP_NEXT_TO=131,
    TD_PREP_WHETHER=132,
    TD_PREP_OFF=133,
    TD_PREP_BESIDE=134,
    TD_PREP_REGARDING=135,
    TD_PREP_VIA=136,
    TD_PREP_BESIDES=137,
    TD_PREP_ABOARD=138,
    TD_PUNCT=139,
    TD_PREPC_UNTIL=140,
    TD_PREP_EXCEPT=141,
    TD_PREP_ALONG_WITH=142,
    TD_PREP_INVOLVING=143,
    TD_CONJ_AND_OR=144,
    TD_PREPC_BETWEEN=145,
    TD_PREP_CLOSE_TO=146,
    TD_PREP_PAST=147,
    TD_PREP_PENDING=148,
    TD_PREP_OUTSIDE_OF=149,
    TD_PREPC_AS=150,
    TD_PREP_FOLLOWING=151,
    TD_PREPC_SUCH_AS=152,
    TD_CONJ=153,
    TD_PREP_UP=154,
    TD_PREPC_THAN=155,
    TD_PREP_IN_PLACE_OF=156,
    TD_PREP_IN_FRONT_OF=157,
    TD_PREP_STARTING=158,
    TD_PREP_DUE_TO=159,
    TD_PREPC_AS_TO=160,
    TD_PREPC_OVER=161,
    TD_PREP_BEYOND=162,
    TD_PREP_REGARDLESS_OF=163,
    TD_PREP_INSIDE_OF=164,
    TD_PREP_PRIOR_TO=165,
    TD_PREP_NEXT=166,
    TD_PREP_THANKS_TO=167,
    TD_PREPC_COMPARED_TO=168,
    TD_PREP_TOWARDS=169,
    TD_PREP_ON_BEHALF_OF=170,
    TD_PREP_OFF_OF=171,
    TD_PREP_TILL=172,
    TD_PREPC_ACROSS_FROM=173,
    TD_PREP_WHILE=174,
    TD_PREPC_THROUGH=175,
    TD_PREPC_BASED_ON=176,
    TD_PREPC_BESIDES=177,
    TD_PREPC_OUT_OF=178,
    TD_PREP_IF=179,
    TD_PREP_BELOW=180,
    TD_PREP_INSTEAD_OF=181,
    TD_PREP_EXCLUDING=182,
    TD_PREPC_NEAR=183,
    TD_PREPC_TOWARD=184,
    TD_PREPC_UPON=185,
    TD_CONJ_JUST=186,
    TD_PREP_DE=187,
    TD_PREP_ACROSS_FROM=188,
    TD_CONJ_ONLY=189,
    TD_PREPC_BELOW=190,
    TD_PREPC_TOGETHER_WITH=191,
    TD_PREPC_LIKE=192,
    TD_PREPC_ALONG_WITH=193,
    TD_PREPC_DEPENDING_ON=194,
    TD_PREP_WORTH=195,
    TD_PREPC_INTO=196,
    TD_CONJ_OF=197,
    TD_PREPC_UP=198,
    TD_PREP_UNLIKE=199,
    TD_PREPC_INSIDE_OF=200,
    TD_PREPC_AMID=201,
    TD_PREPC_NEXT_TO=202,
    TD_PREPC_FOLLOWED_BY=203,
    TD_PREP_FOLLOWED_BY=204,
    TD_PREPC_INSTEAD_OF=205,
    TD_PREPC_ALONG=206,
    TD_CONJ_IN=207,
    TD_PREP_CONTRARY_TO=208,
    TD_PREP_ON_ACCOUNT_OF=209,
    TD_PREPC_BEHIND=210,
    TD_PREPC_AWAY_FROM=211,
    TD_PREPC_THROUGHOUT=212,
    TD_PREP_THOUGH=213,
    TD_PREPC_FOLLOWING=214,
    TD_PREPC_DUE_TO=215,
    TD_PREP_TOGETHER_WITH=216,
    TD_PREPC_EXCEPT=217,
    TD_PREP_FAR_FROM=218,
    TD_PREP_IN_SPITE_OF=219,
    TD_PREPC_WITHIN=220,
    TD_PREPC_DURING=221,
    TD_PREPC_AMONG=222,
    TD_CONJ_IF=223,
    TD_PREP_CONCERNING=224,
    TD_PREP_ON_TOP_OF=225,
    TD_PREPC_AHEAD_OF=226,
    TD_PREPC_AGAINST=227,
    TD_CONJ_VERSUS=228,
    TD_PREPC_BEYOND=229,
    TD_PREP_VS_DOT=230,
    TD_PREPC_ONTO=231,
    TD_CONJ_YET=232,
    TD_PREPC_REGARDLESS_OF=233,
    TD_CONJ_VS_DOT=234,
    TD_PREP_BENEATH=235,
    TD_PREPC_IN_ADDITION_TO=236,
    TD_PREPC_UNDER=237,
    TD_PREP_BARRING=238,
    TD_PREP_BASED_ON=239,
    TD_PREP_NOTWITHSTANDING=240,
    TD_PREPC_PAST=241,
    TD_PREPC_APART_FROM=242,
    TD_PREP_ALTHOUGH=243,
    TD_PREP_AS_FOR=244,
    TD_PREPC_OUT=245,
    TD_PREP_APART_FROM=246,
    TD_PREP_EXCEPT_FOR=247,
    TD_PREPC_PENDING=248,
    TD_PREP_ASIDE_FROM=249,
    TD_PREPC_AS_FOR=250,
    TD_PREPC_ABOVE=251,
    TD_PREP_NEARER=252,
    TD_PREPC_EXCEPT_FOR=253,
    TD_PREP_CONSIDERING=254,
    TD_PREP_SCOUTING=255,
    TD_PREP_UNLESS=256,
    TD_CONJ_THAN=257,
    TD_PREPC_AROUND=258,
    TD_CONJ_MINUS=259,
    TD_PREP_IN_CASE_OF=260,
    TD_PREPC_REGARDING=261,
    TD_PREPC_NEAR_TO=262,
    TD_PREP_SAVE=263,
    TD_PREPC_PRIOR_TO=264,
    TD_PREP_THRU=265,
    TD_CONJ_VS=266,
    TD_PREPC_TOWARDS=267,
    TD_PREP_CLOSE_BY=268,
    TD_PREP_AMIDST=269,
    TD_PREPC_APOS_CAUSE=270,
    TD_PREPC_IN_FRONT_OF=271,
    TD_PREPC_CLOSE_BY=272,
    TD_PREPC_ALONGSIDE=273,
    TD_PREPC_FAR_FROM=274,
    TD_PREPC_IN_SPITE_OF=275,
    TD_PREP_BY_MEANS_OF=276,
    TD_CONJ_APOS_N_APOS=277,
    TD_CONJ_V_DOR=278,
    TD_PREPC_ACROSS=279,
    TD_PREPC_OUTSIDE_OF=280,
    TD_PREP_AS_TO=281,
    TD_PREPC_BECAUSE=282,
    TD_PREPC_ALTHOUGH=283,
    TD_PREP_ACCORDING=284,
    TD_PREP_IN_ACCORDANCE_WITH=285,
    TD_PREP_RACING=286,
    TD_PREP_BEGINNING=287,
    TD_PREPC_OFF=288,
    TD_PREPC_TILL=289,
    TD_PREP_EN=290,
    TD_PREP_WITH_RESPECT_TO=291,
    TD_CONJ_PLUS_SYM=292,
    TD_PREPC_WORTH=293,
    TD_PREP_APOS_TIL=294,
    TD_PREP_IRRESPECTIVE_OF=295,
    TD_PREP_ACCROSS=296,
    TD_PREPC_STARTING=297,
    TD_CONJ_APOS_N=298,
    TD_PREP_UNDERNEATH=299,
    TD_PREPC_WITH_REGARD_TO=300,
    TD_CONJ_THROUGH=301,
    TD_PREP_OPPOSITE=302,
    TD_PREP_ACCORDING_TO=303,
    TD_PREP_THROUGHT=304,
    TD_PREP_HOWST=305,
    TD_UNK=306,
} dep_t;

typedef enum pos_t { PTB_NONE=0, 
                     PTB_CC=1,
                     PTB_CD=2,
			         PTB_DT=3,
                     PTB_EX=4,
                     PTB_FW=5,
                     PTB_IN=6,
                     PTB_JJ=7,
                     PTB_JJR=8,
                     PTB_LS=9,
                     PTB_MD=10,
                     PTB_NN=11,
                     PTB_NNS=12,
                     PTB_NNP=13,
                     PTB_NNPS=14,
                     PTB_PDT=15,
                     PTB_POS=16,
                     PTB_PRP=17,
                     PTB_PRP$=18,
                     PTB_RB=19,
                     PTB_RBR=20,
                     PTB_RBS=21,
                     PTB_RP=22,
                     PTB_SYM=23,
                     PTB_TO=24,
                     PTB_UH=25,
                     PTB_VB=26,
                     PTB_VBD=27,
                     PTB_VBG=28,
                     PTB_VBN=29,
                     PTB_VBP=30,
                     PTB_VBZ=31,
                     PTB_WDT=32,
                     PTB_WP=33,
                     PTB_WP$=34,
                     PTB_WRB=35,
                     PTB_LRB=36,
                     PTB_RRB=37,
                     PTB_JJS=38,
                     PTB_POUND=39,
                     PTB_DOLLARSIGN=40,
                     PTB_PUNC=41
                     } pos_t;

typedef struct sentence_t {
    char **tokens;
    char **lemmas;
    pos_t *pos;
    unsigned int t_len;  
    unsigned int c_len;
    dep_t **deps;
} sentence_t;

typedef struct document_t {
    sentence_t **sentences;
    unsigned int s_len;
} document_t;

typedef struct DBuilder_t {
    GPtrArray *sentences;
    GPtrArray *tokens;
    GPtrArray *lemmas;
    GArray *pos;
    unsigned int cur_t_len;
    unsigned int cur_c_len;
    dep_t **deps; 
} DBuilder_t;


char *cu_sentence_as_string (sentence_t *, gboolean);
char *cu_document_as_string (document_t *);

void cu_sentence_free (sentence_t **sentence, gboolean free_seg);
void cu_document_free (document_t **document, gboolean free_seg);

DBuilder_t *cu_doc_builder_new ();
void cu_doc_builder_new_sentence (DBuilder_t *);
void cu_doc_builder_finish_sentence (DBuilder_t *);
void cu_doc_builder_add_token (DBuilder_t *, char *);
void cu_doc_builder_add_lemma (DBuilder_t *, char *);
void cu_doc_builder_add_pos (DBuilder_t *, pos_t);
void cu_doc_builder_add_dep(DBuilder_t *, int, int, dep_t);

pos_t cu_char_to_pos_t(const char *);
dep_t cu_char_to_dep_t(const char *);

document_t *cu_doc_builder_finalize (DBuilder_t *);
void cu_doc_builder_free (DBuilder_t **, gboolean);

char *cu_pos_string(pos_t);
char *cu_dep_string(dep_t);
//d_builder_t *cnlp_doc_builder_new();
//void cnlp_add_token(d_builder_t *, char *);
//void cnlp_add_sentence(d_builder_t *);

#endif 
